
project_id = "qzwxisdfwswsrbzvpzlo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[functions.whereisit]
verify_jwt = true

[functions.generate-with-groq]
verify_jwt = true

[functions.query-company-data]
verify_jwt = true

[functions.summarize-conversations]
verify_jwt = true
